### PR TITLE
add php cli

### PR DESCRIPTION
**Pull request by yeganehha**
hello
for php cli need to handle empty URL in routing service, i fix this.

and one other thing i see, in gel list of all application in manager app. you put `isCheckHidden` in method parameter but don't use any where

### CODE REVIEW

**Comment by yeganehha** [comment]
sorry i forgot add bellow line in `pincore/service/router.service.php`
`use pinoox\component\Url;`

**Comment by yoosefap** [comment]
> and one other thing i see, in gel list of all application in manager app. you put isCheckHidden in method parameter but don't use any where

$isCheckHidden is a parameter in the method of receiving the list of applications that specifies whether to receive programs that are hidden in the dock or not?

**Comment by yoosefap** [comment]
The following problems were found :

test on php7.3.21
- php pinoox version : Non-static method (should not be called statically)
- php pinoox app:build com_pinoox_welcome : Division by zero & str_repeat() expects parameter 2 to be int

**Comment by yeganehha** [comment]
> > and one other thing i see, in gel list of all application in manager app. you put isCheckHidden in method parameter but don't use any where
> 
> $isCheckHidden is a parameter in the method of receiving the list of applications that specifies whether to receive programs that are hidden in the dock or not?

you add $isCheckHidden parameter in method but don't use any where of method. I add that in correct position inside method

**Comment by yeganehha** [comment]
> test on php7.3.21
> 
> The following problems were found :
> 
> * php pinoox version : Non-static method (should not be called statically)
> * php pinoox app:build com_pinoox_welcome : If the package is not available -> Division by zero & str_repeat() expects parameter 2 to be int

all of them fix and add more command

**Comment by yoosefap** [comment]
Check that in the command to create an installation file of the application (PHP pinoox app:build com_pinoox_paper), why an empty folder named _ will be created in all folders?

**Comment by yeganehha** [comment]
> Check that in the command to create an installation file of the application (PHP pinoox app:build com_pinoox_paper), why an empty folder named _ will be created in all folders?

i check multi time with different php version code but none of them have empty folder with this name ` _`

**Comment by yeganehha** [comment]
some other works is make build index in app.php and add new command for re generate password for users

**Pull request merged**
